language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: UNIT_TESTS=true COMPILER=gcc-5

    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
      env: UNIT_TESTS=true COMPILER=clang-3.8

install:
  ############################################################################
  # All the dependencies are installed in ${TRAVIS_BUILD_DIR}/deps/
  ############################################################################
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}

  ############################################################################
  # Install a recent CMake
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.5/cmake-3.5.1-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew install cmake
    fi

  ############################################################################
  # Get GTest
  ############################################################################
#  - |
#    GTEST_URL="https://github.com/google/googletest/archive/release-1.7.0.tar.gz"
#    mkdir googletest && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
#    export PATH=${DEPS_DIR}/cmake/bin:${PATH}
  - sudo apt-get install -y libgtest-dev
  - cd /usr/src/gtest && sudo cmake -DCMAKE_C_COMPILER=${COMPILER} -DCMAKE_CXX_COMPILER=${COMPILER} . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -

#  - sudo pip install cpp-coveralls

before_script:
  ############################################################################
  # Setup the build directory
  ############################################################################
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build && cd build && cmake -DCMAKE_C_COMPILER=${COMPILER} -DCMAKE_CXX_COMPILER=${COMPILER} ..

script:
  - cmake --build .
  - |
    if [[ "${UNIT_TESTS}" == "true" ]]; then
      test/unit_tests
    fi

#after_success:
#  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"
