language: cpp
sudo: false

matrix:
  include:
    - env: C_COMPILER=gcc-5 CXX_COMPILER=g++-5 UNIT_TESTS=ON CODECOV=ON
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5

    - env: C_COMPILER=clang-3.8 CXX_COMPILER=clang++-3.8 UNIT_TESTS=ON CODECOV=OFF
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8

install:
  ############################################################################
  # All the dependencies are installed in ${TRAVIS_BUILD_DIR}/deps/
  ############################################################################
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}

  ############################################################################
  # Install a recent CMake
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.5/cmake-3.5.1-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew install cmake
    fi

before_script:
  ############################################################################
  # Setup the build directory
  ############################################################################
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build && cd build && cmake -DCMAKE_C_COMPILER=${C_COMPILER} -DCMAKE_CXX_COMPILER=${CXX_COMPILER} -DCODE_COVERAGE={CODECOV} -DGTEST_ROOT=/usr/src/gtest ..

script:
  - cmake --build .
  - |
    if [[ "${UNIT_TESTS}" == "ON" ]]; then
      src/te/tests/te_tests
    fi

after_success:
  - |
    if [[ "${CODECOV}" == "ON" ]]; then
      bash <(curl -s https://codecov.io/bash) -x gcov-5
    fi
