language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: C_COMPILER=gcc-5 CXX_COMPILER=g++-5 UNIT_TESTS=true CODECOV=true

    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
      env: C_COMPILER=clang-3.8 CXX_COMPILER=clang++-3.8 UNIT_TESTS=true CODECOV=false

install:
  ############################################################################
  # All the dependencies are installed in ${TRAVIS_BUILD_DIR}/deps/
  ############################################################################
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}

  ############################################################################
  # Install a recent CMake
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.5/cmake-3.5.1-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew install cmake
    fi

  ############################################################################
  # Get GTest
  ############################################################################
#  - |
#    GTEST_URL="https://github.com/google/googletest/archive/release-1.7.0.tar.gz"
#    mkdir googletest && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
#    export PATH=${DEPS_DIR}/cmake/bin:${PATH}
  - sudo apt-get install -y libgtest-dev
  - cd /usr/src/gtest && sudo cmake -DCMAKE_C_COMPILER=${C_COMPILER} -DCMAKE_CXX_COMPILER=${CXX_COMPILER} . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -

before_script:
  ############################################################################
  # Setup the build directory
  ############################################################################
  - cd ${TRAVIS_BUILD_DIR}
  - |
    if [[ "${CODECOV}" == "true" ]]; then
      CMAKE_CODECOV=-DCMAKE_CXX_FLAGS=-coverage
    fi
  - mkdir build && cd build && cmake -DCMAKE_C_COMPILER=${C_COMPILER} -DCMAKE_CXX_COMPILER=${CXX_COMPILER} ${CMAKE_CODECOV} ..

script:
#  - cmake --build .
  - make VERBOSE=1
  - |
    if [[ "${UNIT_TESTS}" == "true" ]]; then
      te/tests/te_tests
    fi

after_success:
  - |
    if [[ "${CODECOV}" == "true" ]]; then
      bash <(curl -s https://codecov.io/bash) -x gcov-5
    fi
