version: 1.0.{build}

#branches:
#  except:
#    - gh-pages
#
#skip_commits:
#  message: /[ci skip]/

platform:
  - x64
 
configuration:
  - Release

init:
  - git config --global core.autocrlf input

clone_depth: 5
  
install:
  - git submodule update --init --recursive
  
before_build:
  - mkdir build && cd build
  - cmake -G"Visual Studio 14 2015 Win64" ..

build:
  parallel: true
  project: $(APPVEYOR_BUILD_FOLDER)\build\freettcn_te.sln

test_script:
  - ps: echo $env:APPVEYOR_BUILD_FOLDER
  - ps: $env:APPVEYOR_BUILD_FOLDER\build\src\te\tests\Release\te_tests.exe --gtest_output=xml:te_tests.xml

on_finish:
  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\te_tests.xml))
